import { moderateScale, verticalScale } from "utils";

// Used via metrics.baseMargin
const metrics = {
  icons: {
    xsmall: moderateScale(12),
    tiny: moderateScale(15),
    small18: moderateScale(18),
    small: moderateScale(20),
    medium23: moderateScale(23),
    medium25: moderateScale(25),
    medium28: moderateScale(28),
    medium: moderateScale(30),
    large: moderateScale(45),
    xl: moderateScale(50),
    xl100: moderateScale(100),
  },
  borderWidth: {
    bW0: { borderWidth: moderateScale(0) },
    bW05: { borderWidth: moderateScale(0.5) },
    bW1: { borderWidth: moderateScale(1) },
    bW2: { borderWidth: moderateScale(2) },
    bW3: { borderWidth: moderateScale(3) },
    bWL1: { borderLeftWidth: moderateScale(1) },
    bWT1: { borderTopWidth: moderateScale(1) },
    bWB1: { borderBottomWidth: moderateScale(1) },
    bWB2: { borderBottomWidth: moderateScale(2) },
    bWR1: { borderRightWidth: moderateScale(1) },
  },
  border: {
    bR5: { borderRadius: moderateScale(5) },
    bR8: { borderRadius: moderateScale(8) },
    bR10: { borderRadius: moderateScale(10) },
    bR12: { borderRadius: moderateScale(12) },
    bR15: { borderRadius: moderateScale(15) },
    bR20: { borderRadius: moderateScale(20) },
    bR25: { borderRadius: moderateScale(25) },
    bR30: { borderRadius: moderateScale(30) },
    bR50: { borderRadius: moderateScale(50) },
    bR100: { borderRadius: moderateScale(100) },
    bTSR4: { borderTopStartRadius: verticalScale(4) },
    bTSR15: { borderTopStartRadius: verticalScale(15) },
    bTSR25: { borderTopStartRadius: verticalScale(25) },
    bTER4: { borderTopEndRadius: verticalScale(4) },
    bTER15: { borderTopEndRadius: verticalScale(15) },
    bTER25: { borderTopEndRadius: verticalScale(25) },
    bBSR4: { borderBottomStartRadius: verticalScale(4) },
    bBSR10: { borderBottomStartRadius: verticalScale(10) },
    bBSR15: { borderBottomStartRadius: verticalScale(15) },
    bBSR25: { borderBottomStartRadius: verticalScale(25) },
    bBER4: { borderBottomEndRadius: verticalScale(4) },
    bBER10: { borderBottomEndRadius: verticalScale(10) },
    bBER15: { borderBottomEndRadius: verticalScale(15) },
    bBER25: { borderBottomEndRadius: verticalScale(25) },
  },
  paddings: {
    p0: { padding: moderateScale(0) },
    p1: { padding: moderateScale(1) },
    p2: { padding: moderateScale(2) },
    p4: { padding: moderateScale(4) },
    p5: { padding: moderateScale(5) },
    p6: { padding: moderateScale(6) },
    p8: { padding: moderateScale(8) },
    p10: { padding: moderateScale(10) },
    p15: { padding: moderateScale(15) },
    p20: { padding: moderateScale(20) },
    p25: { padding: moderateScale(25) },
    p30: { padding: moderateScale(30) },
    pL0: { paddingLeft: moderateScale(0) },
    pL3: { paddingLeft: moderateScale(3) },
    pL5: { paddingLeft: moderateScale(5) },
    pL8: { paddingLeft: moderateScale(8) },
    pL10: { paddingLeft: moderateScale(10) },
    pL12: { paddingLeft: moderateScale(12) },
    pL15: { paddingLeft: moderateScale(15) },
    pL20: { paddingLeft: moderateScale(20) },
    pL25: { paddingLeft: moderateScale(25) },
    pL30: { paddingLeft: moderateScale(30) },
    pR0: { paddingRight: moderateScale(0) },
    pR5: { paddingRight: moderateScale(5) },
    pR8: { paddingRight: moderateScale(8) },
    pR10: { paddingRight: moderateScale(10) },
    pR15: { paddingRight: moderateScale(15) },
    pR20: { paddingRight: moderateScale(20) },
    pR25: { paddingRight: moderateScale(25) },
    pR30: { paddingRight: moderateScale(30) },
    pT0: { paddingTop: verticalScale(0) },
    pT2: { paddingTop: verticalScale(2) },
    pT4: { paddingTop: verticalScale(4) },
    pT5: { paddingTop: verticalScale(5) },
    pT8: { paddingTop: verticalScale(8) },
    pT10: { paddingTop: verticalScale(10) },
    pT15: { paddingTop: verticalScale(15) },
    pT20: { paddingTop: verticalScale(20) },
    pT25: { paddingTop: verticalScale(25) },
    pT30: { paddingTop: verticalScale(30) },
    pT40: { paddingTop: verticalScale(40) },
    pB0: { paddingBottom: verticalScale(0) },
    pB3: { paddingBottom: verticalScale(3) },
    pB5: { paddingBottom: verticalScale(5) },
    pB8: { paddingBottom: verticalScale(8) },
    pB10: { paddingBottom: verticalScale(10) },
    pB15: { paddingBottom: verticalScale(15) },
    pB20: { paddingBottom: verticalScale(20) },
    pB25: { paddingBottom: verticalScale(25) },
    pB30: { paddingBottom: verticalScale(30) },
    pB65: { paddingBottom: verticalScale(65) },
    pH0: { paddingHorizontal: moderateScale(0) },
    pH2: { paddingHorizontal: moderateScale(2) },
    pH5: { paddingHorizontal: moderateScale(5) },
    pH8: { paddingHorizontal: moderateScale(8) },
    pH10: { paddingHorizontal: moderateScale(10) },
    pH15: { paddingHorizontal: moderateScale(15) },
    pH20: { paddingHorizontal: moderateScale(20) },
    pH25: { paddingHorizontal: moderateScale(25) },
    pH30: { paddingHorizontal: moderateScale(30) },
    pH40: { paddingHorizontal: moderateScale(40) },
    pV0: { paddingVertical: verticalScale(0) },
    pV1: { paddingVertical: verticalScale(1) },
    pV2: { paddingVertical: verticalScale(2) },
    pV3: { paddingVertical: verticalScale(3) },
    pV5: { paddingVertical: verticalScale(5) },
    pV8: { paddingVertical: verticalScale(8) },
    pV12: { paddingVertical: verticalScale(12) },
    pV10: { paddingVertical: verticalScale(10) },
    pV15: { paddingVertical: verticalScale(15) },
    pV20: { paddingVertical: verticalScale(20) },
    pV25: { paddingVertical: verticalScale(25) },
    pV30: { paddingVertical: verticalScale(30) },
    pV40: { paddingVertical: verticalScale(40) },
  },
  margins: {
    m0: { margin: moderateScale(0) },
    m5: { margin: moderateScale(5) },
    m10: { margin: moderateScale(10) },
    m15: { margin: moderateScale(15) },
    m20: { margin: moderateScale(20) },
    m25: { margin: moderateScale(25) },
    m30: { margin: moderateScale(30) },
    mL0: { marginLeft: moderateScale(0) },
    mL5: { marginLeft: moderateScale(5) },
    mL8: { marginLeft: moderateScale(8) },
    mL10: { marginLeft: moderateScale(10) },
    mL15: { marginLeft: moderateScale(15) },
    mL20: { marginLeft: moderateScale(20) },
    mL25: { marginLeft: moderateScale(25) },
    mL30: { marginLeft: moderateScale(30) },
    mR0: { marginRight: moderateScale(0) },
    mR5: { marginRight: moderateScale(5) },
    mR8: { marginRight: moderateScale(8) },
    mR10: { marginRight: moderateScale(10) },
    mR12: { marginRight: moderateScale(12) },
    mR15: { marginRight: moderateScale(15) },
    mR20: { marginRight: moderateScale(20) },
    mR25: { marginRight: moderateScale(25) },
    mR30: { marginRight: moderateScale(30) },
    mT0: { marginTop: verticalScale(0) },
    mT3: { marginTop: verticalScale(3) },
    mT5: { marginTop: verticalScale(5) },
    mT8: { marginTop: verticalScale(8) },
    mT10: { marginTop: verticalScale(10) },
    mT12: { marginTop: moderateScale(12) },
    mT15: { marginTop: verticalScale(15) },
    mT20: { marginTop: verticalScale(20) },
    mT25: { marginTop: verticalScale(25) },
    mT30: { marginTop: verticalScale(30) },
    mB0: { marginBottom: verticalScale(0) },
    mB5: { marginBottom: verticalScale(5) },
    mB8: { marginBottom: verticalScale(8) },
    mB10: { marginBottom: verticalScale(10) },
    mB15: { marginBottom: verticalScale(15) },
    mB20: { marginBottom: verticalScale(20) },
    mB25: { marginBottom: verticalScale(25) },
    mB30: { marginBottom: verticalScale(30) },
    mB40: { marginBottom: verticalScale(40) },
    mB100: { marginBottom: verticalScale(100) },
    mH0: { marginHorizontal: moderateScale(0) },
    mH3: { marginHorizontal: moderateScale(3) },
    mH5: { marginHorizontal: moderateScale(5) },
    mH10: { marginHorizontal: moderateScale(10) },
    mH15: { marginHorizontal: moderateScale(15) },
    mH20: { marginHorizontal: moderateScale(20) },
    mH25: { marginHorizontal: moderateScale(25) },
    mH30: { marginHorizontal: moderateScale(30) },
    mV0: { marginVertical: verticalScale(0) },
    mV2: { marginVertical: verticalScale(2) },
    mV4: { marginVertical: verticalScale(4) },
    mV5: { marginVertical: verticalScale(5) },
    mV8: { marginVertical: verticalScale(8) },
    mV10: { marginVertical: verticalScale(10) },
    mV15: { marginVertical: verticalScale(15) },
    mV20: { marginVertical: verticalScale(20) },
    mV25: { marginVertical: verticalScale(25) },
    mV30: { marginVertical: verticalScale(30) },
  },
};

export default metrics;
